default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: mario
  password: 123mudar
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contact_agenda_development

test:
  <<: *default
  database: contact_agenda_test

production:
  <<: *default
  database: contact_agenda_production
  username: contact_agenda
  password: <%= ENV["CONTACT_AGENDA_DATABASE_PASSWORD"] %>
